/*
 Copyright 2011-2016 Adobe Systems Incorporated. All Rights Reserved.
*/
(function(d){"function"===typeof define&&define.amd&&define.amd.jQuery?define(["jquery","museutils"],d):d(jQuery)})(function(d){function b(a){var b=a.css("background-image");a.css("background-image","");var c=a.css("background-image");b!=c&&a.css("background-image",b);return c.replace(/^\s*url\(\"?/,"").replace(/['"]?\)$/,"")}if(!Muse.Browser.Features.checkCSSFeature("background-size")){var c=function(a){var c=d(a),f=b(c),i=document.createElement("img"),h=document.createElement("div"),l=this,k=!1,
m=!1,n=!0,p={};d(h).css({overflow:"hidden",position:"absolute",top:"0px",left:"0px",width:a.clientWidth+"px",height:a.clientHeight+"px",marginBottom:"-"+a.clientHeight+"px",marginRight:"-"+a.clientWidth+"px",zIndex:"-1"}).addClass("museBgSizePolyfill");i.src=f;i.alt="";i.style.position="absolute";h.appendChild(i);a.children.length>0?a.insertBefore(h,a.children[0]):a.appendChild(h);if(a===document.body)c=d("html"),a=c.get(0),f=b(c),i.src=f,c.css("background-attachment")=="fixed"?(h.style.position=
"fixed",n=!1):h.style.position="absolute";else if(c.is("#page"))c.css("marginLeft").toLowerCase()=="auto"&&(m=!0),h.style.top=c.offset().top+parseInt(c.css("borderTopWidth"))+"px",h.style.bottom=parseInt(c.parent().css("paddingBottom"))+parseInt(c.css("borderBottomWidth"))+"px",h.style.left=c.offset().left+parseInt(c.css("borderLeftWidth"))+"px",h.style.right=c.offset().left+parseInt(c.css("borderRightWidth"))+"px",h.style.zIndex=0;else if(c.css("position")=="static")a.style.position="relative";this.reloadImage=
function(){var d=b(c),f=c.css("background-color");if(d!=i.src)i.src=d;a.style.backgroundImage="none";a.style.backgroundColor="transparent";h.style.backgroundColor=f;d=(c.css("background-position-x")+" "+c.css("background-position-y")).replace(/^\s+/,"").replace(/\s+$/,"");"0px 0px"==d&&(d="left top");d=d.split(/\s+/);d.length==1&&d[0].indexOf("center")>=0&&d.push("center");if(c.data("hasBackgroundPositionScrollEffect")!=!0)for(var f=0,k=d.length;f<k;f++)switch(d[f]){case "center":case "50%":f==0?
(i.style.right="",i.style.left="50%",i.style.marginLeft="-"+Math.ceil(i.offsetWidth/2)+"px"):(i.style.bottom="",i.style.top="50%",i.style.marginTop="-"+Math.ceil(i.offsetHeight/2)+"px");break;case "left":i.style.right="";i.style.left="0px";i.style.marginLeft="0px";break;case "right":i.style.left="";i.style.right="0px";i.style.marginLeft="0px";break;case "top":i.style.bottom="";i.style.top="0px";i.style.marginTop="0px";break;case "bottom":i.style.top="";i.style.bottom="0px";i.style.marginTop="0px";
break;default:f==0?(i.style.left=d[f],i.style.marginLeft="-"+Math.ceil(i.offsetWidth/2)+"px"):(i.style.top=d[f],i.style.marginTop="-"+Math.ceil(i.offsetHeight/2)+"px")}};this.resizeImage=function(b){var d=a.getBoundingClientRect(),f=a.scrollWidth-(Muse.Browser.Bugs.ScrollWidthHeightIncludesBorder?d.right-d.left-c.innerWidth():0),d=a.scrollHeight-(Muse.Browser.Bugs.ScrollWidthHeightIncludesBorder?d.bottom-d.top-c.innerHeight():0),f=!n?a.clientWidth:Math.max(f,a.clientWidth),d=!n?a.clientHeight:Math.max(d,
a.clientHeight);!p[i.src]&&i.clientWidth&&(p[i.src]={width:i.clientWidth,height:i.clientHeight});var k=f/(p[i.src]?p[i.src].width:1),l=d/(p[i.src]?p[i.src].height:1);h.style.height=d+"px";h.style.marginBottom="-"+d+"px";h.style.width=f+"px";h.style.marginRight="-"+f+"px";k<l==b?(i.style.height=d+1+"px",i.style.width="auto"):(i.style.width=f+1+"px",i.style.height="auto")};this.update=function(){if(k){a.style.backgroundImage="";c.css("background-color","");var b=c.css("background-image").toLowerCase(),
d=(a.currentStyle||window.getComputedStyle(a,null))["background-size"];d&&d.toLowerCase();if(b!="none"&&(d=="cover"||d=="contain")){if(l.reloadImage(),h.style.display="block",h.style.width="0px",h.style.height="0px",l.resizeImage(d=="cover"),m)h.style.left=c.offset().left+parseInt(c.css("borderLeftWidth"))+"px",h.style.right=c.offset().left+parseInt(c.css("borderRightWidth"))+"px"}else h.style.display="none"}};if(i.complete||f=="none")k=!0;else d(i).one("load",function(){k=!0;l.update()});this.update()},
a=function(){this.updateList=[]};a.prototype.initialize=function(a){var b=this;a.each(function(){var a=new c(this);this!==document.body?b.updateList.push(a):(d(window).resize(function(){setTimeout(function(){a.update()},10)}),d(window).load(function(){setTimeout(function(){a.update()},10)}))});var f=b.updateList.length;f>0&&setInterval(function(){for(var a=0;a<f;a++)b.updateList[a].update()},Math.max(120,16*f))};d(window).data("musePolyfill.bgSize",new a)}});
;(function(){if(!("undefined"==typeof Muse||"undefined"==typeof Muse.assets)){var a=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return c;return-1}(Muse.assets.required,"jquery.musepolyfill.bgsize.js");if(-1!=a){Muse.assets.required.splice(a,1);for(var a=document.getElementsByTagName("meta"),b=0,c=a.length;b<c;b++){var d=a[b];if("generator"==d.getAttribute("name")){"2015.2.1.352"!=d.getAttribute("content")&&Muse.assets.outOfDate.push("jquery.musepolyfill.bgsize.js");break}}}}})();
